language: docker

services:
  - docker

before_install:
  - echo "Logging into Docker Hub..."
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

script:
  - echo "start..."
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed thawngs2405/udagram-api-feed:v2.1
  - docker push thawngs2405/udagram-api-feed:v2.1
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user thawngs2405/udagram-api-user:v2.1
  - docker push thawngs2405/udagram-api-user:v2.1
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy thawngs2405/reverseproxy:v2.1
  - docker push thawngs2405/reverseproxy:v2.1
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend thawngs2405/udagram-frontend:v2.1
  - docker push thawngs2405/udagram-frontend:v2.1
  - docker images
  #- kubectl apply -f env-configmap.yaml
  #- kubectl apply -f env-secret.yaml
  #- kubectl apply -f aws-secret.yaml
  #- kubectl apply -f backend-feed-deployment.yaml
  #- kubectl apply -f backend-user-deployment.yaml
  #- kubectl apply -f frontend-deployment.yaml
  #- kubectl apply -f reverseproxy-deployment.yaml
  - echo "end."

notifications:
  email:
    recipients:
      - thang24052001nguyen@gmail.com
    on_success: always
    on_failure: always
