language: docker  # Sử dụng Docker làm môi trường xây dựng

services:
  - docker  # Dịch vụ Docker để có thể xây dựng và chạy các container

# Các bước trước khi cài đặt
before_install:
  - echo "Logging into Docker Hub..."
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD  # Đăng nhập vào Docker Hub

# Xây dựng và đẩy Docker images
script:
  - echo "start..."
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed thawngs2405/udagram-api-feed:v2.0
  - docker push thawngs2405/udagram-api-feed:v2.0
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user thawngs2405/udagram-api-user:v2.0
  - docker push thawngs2405/udagram-api-user:v2.0
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy thawngs2405/reverseproxy:v2.0
  - docker push thawngs2405/reverseproxy:v2.0
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend thawngs2405/udagram-frontend:v2.0
  - docker push thawngs2405/udagram-frontend:v2.0
  - docker images
  #- kubectl apply -f env-configmap.yaml
  #- kubectl apply -f env-secret.yaml
  #- kubectl apply -f aws-secret.yaml
  #- kubectl apply -f backend-feed-deployment.yaml
  #- kubectl apply -f backend-user-deployment.yaml
  #- kubectl apply -f frontend-deployment.yaml
  #- kubectl apply -f reverseproxy-deployment.yaml
  - echo "end."

# Thêm thông báo (tùy chọn)
notifications:
  email:
    recipients:
      - thang24052001nguyen@gmail.com  # Địa chỉ email nhận thông báo
    on_success: always  # Thông báo khi build thành công
    on_failure: always  # Thông báo khi build thất bại
