language: docker  # Sử dụng Docker làm môi trường xây dựng

services:
  - docker  # Dịch vụ Docker để có thể xây dựng và chạy các container

# Các bước trước khi cài đặt
before_install:
  - echo "Logging into Docker Hub..."
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD  # Đăng nhập vào Docker Hub

# Xây dựng và đẩy Docker images
script:
  - echo "start..."
  - source set_env.sh
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed thawngs2405/udagram-api-feed:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push thawngs2405/udagram-api-feed:v1
  - echo "end."

# Thêm thông báo (tùy chọn)
notifications:
  email:
    recipients:
      - thang24052001nguyen@gmail.com  # Địa chỉ email nhận thông báo
    on_success: always  # Thông báo khi build thành công
    on_failure: always  # Thông báo khi build thất bại
