language: docker  # Sử dụng Docker làm môi trường xây dựng

services:
  - docker  # Dịch vụ Docker để có thể xây dựng và chạy các container

# Các bước trước khi cài đặt
before_install:
  - echo "Logging into Docker Hub..."
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD  # Đăng nhập vào Docker Hub

# Xây dựng và đẩy Docker images
script:
  - echo "Building Docker image for udagram-api-user..."
  - docker build -t $DOCKER_USERNAME/udagram-api-user ./udagram-api-user  # Xây dựng hình ảnh của dịch vụ người dùng
  - echo "Pushing Docker image for udagram-api-user to Docker Hub..."
  - docker push $DOCKER_USERNAME/udagram-api-user  # Đẩy lên Docker Hub

  - echo "Building Docker image for udagram-api-feed..."
  - docker build -t $DOCKER_USERNAME/udagram-api-feed ./udagram-api-feed  # Xây dựng hình ảnh của dịch vụ feed
  - echo "Pushing Docker image for udagram-api-feed to Docker Hub..."
  - docker push $DOCKER_USERNAME/udagram-api-feed  # Đẩy lên Docker Hub

  - echo "Building Docker image for udagram-frontend..."
  - docker build -t $DOCKER_USERNAME/udagram-frontend ./udagram-frontend  # Xây dựng hình ảnh của frontend
  - echo "Pushing Docker image for udagram-frontend to Docker Hub..."
  - docker push $DOCKER_USERNAME/udagram-frontend  # Đẩy lên Docker Hub

  - echo "Building Docker image for udagram-reverseproxy..."
  - docker build -t $DOCKER_USERNAME/udagram-reverseproxy ./udagram-reverseproxy  # Xây dựng hình ảnh của reverseproxy
  - echo "Pushing Docker image for udagram-reverseproxy to Docker Hub..."
  - docker push $DOCKER_USERNAME/udagram-reverseproxy  # Đẩy lên Docker Hub

# Thêm thông báo (tùy chọn)
notifications:
  email:
    recipients:
      - thang24052001nguyen@gmail.com  # Địa chỉ email nhận thông báo
    on_success: always  # Thông báo khi build thành công
    on_failure: always  # Thông báo khi build thất bại
