apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: thawngs2405/udagram-api-feed:v2.1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: db-credentials
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: aws_secret_access_key
          - name: AWS_REGION
            value: "us-east-1"
        resources:
          requests:
            cpu: "100m"
            memory: "2048Mi"
          limits:
            cpu: "1000m"
            memory: "10240Mi"