apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: thawngs2405/udagram-api-user:v2.1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: db-credentials
        resources:
          requests:
            cpu: "100m"
            memory: "2048Mi"
          limits:
            cpu: "1000m"
            memory: "10240Mi"
