apiVersion: v1
kind: Service
metadata:
  name: backend-feed-service
spec:
  type: ClusterIP  # Dịch vụ chỉ cần truy cập nội bộ
  ports:
  - port: 8080      # Cổng nội bộ cluster
    targetPort: 8080 # Cổng trong container
  selector:
    app: backend-feed
