apiVersion: v1
kind: Service
metadata:
  name: backend-user-service
spec:
  type: ClusterIP  # Dịch vụ chỉ cần truy cập nội bộ
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: backend-user
