apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: thawngs2405/udagram-frontend:v2.1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "2048Mi"
          limits:
            cpu: "1000m"
            memory: "10240Mi"