apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: thawngs2405/reverseproxy:v2.1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "2048Mi"
          limits:
            cpu: "1000m"
            memory: "10240Mi"
